global using Microsoft.EntityFrameworkCore;
global using HospitalManagementSystem.Domain;
global using HospitalManagementSystem.Application;
global using HospitalManagementSystem.ServiceProvider;
global using System.Linq.Expressions;
global using Microsoft.OpenApi.Models;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;