global using AutoMapper;
global using AutoMapper.QueryableExtensions;
global using HospitalManagementSystem.Domain;
global using HospitalManagementSystem.Application;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using System.Text.RegularExpressions;
global using System.Linq.Expressions;
global using System.Diagnostics;