global using OneOf;
global using IdentitySystem.Application;
global using IdentitySystem.DataProvider;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Security.Principal;
global using System.Text;