// <auto-generated />
using System;
using HospitalManagementSystem.DataProvider;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalManagementSystem.Context.Migrations
{
    [DbContext(typeof(HospitalManagementSystemDbContext))]
    [Migration("20240410135928_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.AnalysisTest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DSymptom")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("DeviceServiceId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("DoctorComment")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("MedicalExamEposodeId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("AnalysisTest");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.AssignmentHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<string>("AssignmentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("MedicalExamEposodeId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ReferralDoctorId")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.ToTable("AssignmentHistory");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.BookingAppointment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("BookingAppointment");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.DeviceInventory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("CurrentAmount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("MedicalDeviceId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("StorageId")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.ToTable("DeviceInventory");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.DeviceService", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("DeviceInventoryId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("ServiceId")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.ToTable("DeviceService");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Diagnosis", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar");

                    b.Property<string>("DiagnosisCode")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ICDId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Diagnosis");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.DiagnosisTreatment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("DiagnosisId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("TreatmentId")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.ToTable("DiagnosisTreatment");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Drug", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ActiveIngredientName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("GoodName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.Property<string>("GoodType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<string>("HealthInsurancePrice")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.Property<string>("UnitPrice")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Drug");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.DrugInventory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("CurrentAmount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("GoodSupplingId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("StorageId")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.ToTable("DrugInventory");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.DrugPrescription", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("DrugInventoryId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("MedicalExamEposodeId")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.ToTable("DrugPrescription");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.GoodSuppling", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("DrugId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GoodInformation")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ImportationId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int>("OrinaryAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GoodSuppling");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.ICD", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("ICD");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Importation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Billnumber")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ReceiptDay")
                        .HasColumnType("datetime");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("RecordDay")
                        .HasColumnType("datetime");

                    b.Property<int>("Tax")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Importation");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.MedicalDevice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("GroupID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int>("Max")
                        .HasColumnType("int");

                    b.Property<int>("Min")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.Property<string>("SmallID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("MedicalDevice");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.MedicalExam", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<string>("BookingAppointmentId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int?>("FinalPrice")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("MedicalExam");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.MedicalExamEposode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateReExam")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTakeExam")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("MedicalExamId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("RecordDay")
                        .HasColumnType("datetime");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MedicalExamEposode");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.ReExamAppointment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("MedicalExamEposodeId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("ReExamAppointment");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Referral", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateOfReferral")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("MedicalExamId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Referral");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.ReferralDoctor", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("ReferralId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ReferralStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.Property<string>("ReferredDoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("ReferralDoctor");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.RoomAllocation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("MedicalExamEposodeId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.Property<string>("RoomId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("RoomAllocation");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.RoomAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("RoomId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("RoomAssignment");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Service", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int>("HealthInsurancePrice")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ResultFromType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.Property<int>("ServicePrice")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Storage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Storage");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Treatment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Treatment");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.TreatmentExamEpisode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("MedicalExamEpisodeId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("TreatmentId")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.ToTable("TreatmentExamEpisode");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.AnalysisTest", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.DeviceService", "DeviceService")
                        .WithMany("AnalysisTests")
                        .HasForeignKey("DeviceServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.DataProvider.MedicalExamEposode", "MedicalExamEposode")
                        .WithMany("AnalysisTests")
                        .HasForeignKey("MedicalExamEposodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceService");

                    b.Navigation("MedicalExamEposode");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.AssignmentHistory", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.MedicalExamEposode", "MedicalExamEposode")
                        .WithMany("AssignmentHistories")
                        .HasForeignKey("MedicalExamEposodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.DataProvider.ReferralDoctor", "ReferralDoctor")
                        .WithOne("AssignmentHistory")
                        .HasForeignKey("HospitalManagementSystem.DataProvider.AssignmentHistory", "ReferralDoctorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MedicalExamEposode");

                    b.Navigation("ReferralDoctor");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.DeviceInventory", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.MedicalDevice", "MedicalDevice")
                        .WithMany("DeviceInventorys")
                        .HasForeignKey("MedicalDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.DataProvider.Storage", "Storage")
                        .WithMany("DeviceInventories")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalDevice");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.DeviceService", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.DeviceInventory", "DeviceInventory")
                        .WithMany("DeviceServices")
                        .HasForeignKey("DeviceInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.DataProvider.Service", "Service")
                        .WithMany("DeviceServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceInventory");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Diagnosis", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.ICD", "ICD")
                        .WithMany("Diagnoses")
                        .HasForeignKey("ICDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ICD");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.DiagnosisTreatment", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.Diagnosis", "Diagnosis")
                        .WithMany("DiagnosisTreatments")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.DataProvider.Treatment", "Treatment")
                        .WithMany("DiagnosisTreatments")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.DrugInventory", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.GoodSuppling", "GoodSuppling")
                        .WithOne("DrugInventory")
                        .HasForeignKey("HospitalManagementSystem.DataProvider.DrugInventory", "GoodSupplingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.DataProvider.Storage", "Storage")
                        .WithMany("DrugInventories")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodSuppling");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.DrugPrescription", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.DrugInventory", "DrugInventory")
                        .WithMany("DrugPrescriptions")
                        .HasForeignKey("DrugInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.DataProvider.MedicalExamEposode", "MedicalExamEposode")
                        .WithMany("DrugPrescriptions")
                        .HasForeignKey("MedicalExamEposodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrugInventory");

                    b.Navigation("MedicalExamEposode");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.GoodSuppling", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.Drug", "Drug")
                        .WithMany("GoodSupplings")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.DataProvider.Importation", "Importation")
                        .WithMany("GoodSupplings")
                        .HasForeignKey("ImportationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Importation");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.MedicalExam", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.BookingAppointment", "BookingAppointment")
                        .WithOne("MedicalExam")
                        .HasForeignKey("HospitalManagementSystem.DataProvider.MedicalExam", "BookingAppointmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BookingAppointment");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.MedicalExamEposode", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.MedicalExam", "MedicalExam")
                        .WithMany("MedicalExamEposodes")
                        .HasForeignKey("MedicalExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalExam");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.ReExamAppointment", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.MedicalExamEposode", "MedicalExamEposode")
                        .WithOne("ReExamAppointment")
                        .HasForeignKey("HospitalManagementSystem.DataProvider.ReExamAppointment", "MedicalExamEposodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalExamEposode");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Referral", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.MedicalExam", "MedicalExam")
                        .WithMany("Referrals")
                        .HasForeignKey("MedicalExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalExam");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.ReferralDoctor", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.Referral", "Referral")
                        .WithMany("ReferralDoctors")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Room", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.RoomAllocation", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.MedicalExamEposode", "MedicalExamEposode")
                        .WithMany("RoomAllocations")
                        .HasForeignKey("MedicalExamEposodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.DataProvider.Room", "Room")
                        .WithMany("RoomAllocations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalExamEposode");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.RoomAssignment", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.Room", "Room")
                        .WithMany("RoomAssignments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.TreatmentExamEpisode", b =>
                {
                    b.HasOne("HospitalManagementSystem.DataProvider.MedicalExamEposode", "MedicalExamEposode")
                        .WithMany("TreatmentExamEpisodes")
                        .HasForeignKey("MedicalExamEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.DataProvider.Treatment", "Treatment")
                        .WithMany("TreatmentExamEpisodes")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalExamEposode");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.BookingAppointment", b =>
                {
                    b.Navigation("MedicalExam");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Department", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.DeviceInventory", b =>
                {
                    b.Navigation("DeviceServices");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.DeviceService", b =>
                {
                    b.Navigation("AnalysisTests");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Diagnosis", b =>
                {
                    b.Navigation("DiagnosisTreatments");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Drug", b =>
                {
                    b.Navigation("GoodSupplings");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.DrugInventory", b =>
                {
                    b.Navigation("DrugPrescriptions");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.GoodSuppling", b =>
                {
                    b.Navigation("DrugInventory");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.ICD", b =>
                {
                    b.Navigation("Diagnoses");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Importation", b =>
                {
                    b.Navigation("GoodSupplings");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.MedicalDevice", b =>
                {
                    b.Navigation("DeviceInventorys");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.MedicalExam", b =>
                {
                    b.Navigation("MedicalExamEposodes");

                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.MedicalExamEposode", b =>
                {
                    b.Navigation("AnalysisTests");

                    b.Navigation("AssignmentHistories");

                    b.Navigation("DrugPrescriptions");

                    b.Navigation("ReExamAppointment");

                    b.Navigation("RoomAllocations");

                    b.Navigation("TreatmentExamEpisodes");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Referral", b =>
                {
                    b.Navigation("ReferralDoctors");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.ReferralDoctor", b =>
                {
                    b.Navigation("AssignmentHistory");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Room", b =>
                {
                    b.Navigation("RoomAllocations");

                    b.Navigation("RoomAssignments");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Service", b =>
                {
                    b.Navigation("DeviceServices");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Storage", b =>
                {
                    b.Navigation("DeviceInventories");

                    b.Navigation("DrugInventories");
                });

            modelBuilder.Entity("HospitalManagementSystem.DataProvider.Treatment", b =>
                {
                    b.Navigation("DiagnosisTreatments");

                    b.Navigation("TreatmentExamEpisodes");
                });
#pragma warning restore 612, 618
        }
    }
}
